### ISSUE TITLE
Error running plugin Autodock plugin

### ISSUE THREAD

**Issue by houdini69** [Pymol-Scripts/Pymol-script-repo#122]
How to fix this issue when running Autodock plugin (Pymol 2.5.0 on macOS 10.13.6)?
```
Traceback (most recent call last):
  File "/Users/xxxxxxxxxxx/.pymol/startup/autodock_plugin.py", line 109, in <lambda>
    command=lambda s=self: Autodock(s))
  File "/Users/xxxxxxxxxxx/.pymol/startup/autodock_plugin.py", line 590, in __init__
    self.notebook = Pmw.NoteBook(self.dialog.interior())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Pmw/Pmw_2_0_1/lib/PmwNoteBook.py", line 60, in __init__
    Pmw.Color.bordercolors(self, self['hull_background'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Pmw/Pmw_2_0_1/lib/PmwColor.py", line 359, in bordercolors
    '#%04x%04x%04x' % (lightRGB[0], lightRGB[1], lightRGB[2]),
TypeError: %x format: an integer is required, not float
```

**Comment by houdini69** [comment]
Applied successfully this [patch](https://github.com/schrodinger/pmw-patched) and now Pymol autodock/vina plugin starts,
